name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Install wasm-opt
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: WebAssembly/binaryen
          tag: version_117
          binaries-location: binaryen-version_117/bin
          platform: linux
          arch: x86_64
      - name: Check available
        run: which wasm-opt